sudo: required
services:
  - docker

before_install:
  - docker build -t benobringer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true benobringer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-686583715967"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"